server:
  port: 8081

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8082
---
spring:
  profiles: test
server:
  port: 8083
---
spring:
  profiles: prod
server:
  port: 8084